name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: Set up Git config
        run: |
          git config user.name sumedhbadnore
          git config user.email sumedhbadnore2801@gmail.com
          
      - name: Install dependencies
        run: npm install
        working-directory: ./portfolio

      - name: Build project
        run: npm run build
        working-directory: ./portfolio

      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: ./portfolio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
